Adding OCP 4.13 zstream jobs
Signed-off-by: Varad Ahirwadkar <varad.ahirwadkar@ibm.com>

diff --git a/jobs/pipelines/powervm/ocp/zstreams/p9_jobs/zstream-ocp4x-p9-min-next-upgrade/Jenkinsfile b/jobs/pipelines/powervm/ocp/zstreams/p9_jobs/zstream-ocp4x-p9-min-next-upgrade/Jenkinsfile
--- a/jobs/pipelines/powervm/ocp/zstreams/p9_jobs/zstream-ocp4x-p9-min-next-upgrade/Jenkinsfile
+++ b/jobs/pipelines/powervm/ocp/zstreams/p9_jobs/zstream-ocp4x-p9-min-next-upgrade/Jenkinsfile
@@ -9,11 +9,12 @@ pipeline {
         }
     }
     parameters {
-        string(defaultValue: '', description: 'Build(quay image or build number)', name: 'Build')
-        string(defaultValue: '', description: 'Build Release', name: 'Release')
+        string(defaultValue: '', description: 'Current Build(quay image or build number)', name: 'CurrentBuild')
+        string(defaultValue: '', description: 'Upgrade Build(quay image or build number)', name: 'UpgradeBuild')
+        string(defaultValue: '', description: 'Current Build Release', name: 'Release')
+        string(defaultValue: '', description: 'Upgrade Build Release', name: 'UpgradeRelease')
         string(defaultValue: '720', description: 'Enter time(in Minutes) to retain the cluster', name: 'KeepFor')
     }
-
     environment {
         //users and credentials. All must be defined in Jenkins Credentials
         GITHUB_USER = credentials('GITHUB_USER')
@@ -33,17 +34,18 @@ pipeline {
 
         //Parameters
         OCP_RELEASE="${params.Release}"
+        UPGRADE_RELEASE="${params.UpgradeRelease}"
         CONFIG_TYPE="min"
-        BUILD="${params.Build}"
+        CURRENT_BUILD="${params.CurrentBuild}"
+        UPGRADE_BUILD="${params.UpgradeBuild}"
         TIMEOUT = "${params.KeepFor}"
-        ENABLE_E2E_TEST="true"
 
         //Branch
         OPENSHIFT_POWERVC_GIT_TF_DEPLOY_BRANCH="main"//The download branch
 
         //Env constants
-        HARDWARE_CHOSE = "P8"
-        AVAILABILITY_ZONE = "p8-new"
+        HARDWARE_CHOSE = "P9"
+        AVAILABILITY_ZONE = "workload"
         TARGET = "deploy-openshift4-powervc"
         TEMPLATE_FILE = ".${TARGET}.tfvars.template"
         TERRAFORM_VER = "1.2.0"
@@ -54,36 +56,28 @@ pipeline {
     }
 
     stages {
-        stage('Clone ansible extra') {
-            steps {
-                cloneRepo("https://github.com/ocp-power-automation/ocp4-playbooks-extras", "ocp4-playbooks-extras", "*/main")
-            }
-        }
         stage('Setup Common Environment Variables') {
             steps {
                 setupCommonEnvironmentVariables()
                 setupClusterConfig("${CONFIG_TYPE}")
                 script {
                     wrap([$class: 'BuildUser']) {
-                        env.INSTANCE_NAME = "rdr-zstream"
+                        env.INSTANCE_NAME = "rdr-zsnxt-p9"
                     }
                     env.OS_TENANT_NAME="icp-test"
                     env.OS_NETWORK = "workload"
                     env.OS_PRIVATE_NETWORK = "workload"
                     env.SCG_ID = "4366c1e2-bb4f-4c3d-98a2-06cc39bbc58d"
                     env.MOUNT_ETCD_RAMDISK = "false"
+                    env.UPGRADE_DELAY_TIME = "600"
+                    env.UPGRADE_PAUSE_TIME = "90"
                     env.SETUP_SQUID_PROXY = "true"
-                    if (env.OCP_RELEASE == "4.8" || env.OCP_RELEASE == "4.9"){
-                        env.REDHAT_RELEASE = "8.4"
-                        env.GOLANG_TARBALL = "https://dl.google.com/go/go1.16.5.linux-ppc64le.tar.gz"
-                    }
-                    else if (env.OCP_RELEASE == "4.10" || env.OCP_RELEASE == "4.11"){
-                        env.REDHAT_RELEASE = "8.5"
-                        env.GOLANG_TARBALL = "https://dl.google.com/go/go1.17.6.linux-ppc64le.tar.gz"
+
+                    if (env.OCP_RELEASE == "4.12"){
+                        env.REDHAT_RELEASE = "8.6"
                     }
                     else {
-                        env.REDHAT_RELEASE = "8.6"
-                        env.GOLANG_TARBALL = "https://golang.org/dl/go1.18.6.linux-ppc64le.tar.gz"
+                        env.REDHAT_RELEASE = "9.2"
                     }
                 }
             }
@@ -108,24 +102,45 @@ pipeline {
                         gbToMb()
                         pullSecret()
                         env.OPENSHIFT_IMAGE = ""
-                        if (env.BUILD?.trim()) {
-                            if (!env.BUILD.contains('quay')) {
-                                env.OPENSHIFT_IMAGE  = "sys-powercloud-docker-local.artifactory.swg-devops.com/ocp-ppc64le/release-ppc64le:${env.BUILD}"
+                        if (env.CURRENT_BUILD?.trim()) {
+                            if (!env.CURRENT_BUILD.contains('quay')) {
+                                env.OPENSHIFT_IMAGE  = "sys-powercloud-docker-local.artifactory.swg-devops.com/ocp-ppc64le/release-ppc64le:${env.CURRENT_BUILD}"
                                 sh '''
                                     nerdctl login sys-powercloud-docker-local.artifactory.swg-devops.com -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
                                     nerdctl pull ${OPENSHIFT_IMAGE}
                                     if [ $? -ne 0 ]; then
-                                        echo "${OPENSHIFT_IMAGE}  not found"
+                                        echo "${OPENSHIFT_IMAGE} not found"
                                         exit 1
                                     fi
                                 '''
                             }
                             else {
-                               env.OPENSHIFT_IMAGE=env.BUILD
+                               env.OPENSHIFT_IMAGE=env.CURRENT_BUILD
                             }
                         }
                         else {
                             echo "CURRENT build is empty"
+                            throw err
+                        }
+                        env.UPGRADE_IMAGE = ""
+                        if (env.UPGRADE_BUILD?.trim()) {
+                            if (!env.UPGRADE_BUILD.contains('quay')) {
+                                env.UPGRADE_IMAGE  = "sys-powercloud-docker-local.artifactory.swg-devops.com/ocp-ppc64le/release-ppc64le:${env.UPGRADE_BUILD}"
+                                sh '''
+                                    nerdctl login sys-powercloud-docker-local.artifactory.swg-devops.com -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
+                                    nerdctl pull ${UPGRADE_IMAGE}
+                                    if [ $? -ne 0 ]; then
+                                        echo "${UPGRADE_IMAGE} not found"
+                                        exit 1
+                                    fi
+                                '''
+                            }
+                            else {
+                               env.UPGRADE_IMAGE=env.UPGRADE_BUILD
+                            }
+                        }
+                        else{
+                            echo "Upgrade build is empty"
                             throw err
                         }
                         if (fileExists("deploy/artifactory/rhcos-${OCP_RELEASE}-powercloud-latest.txt")) {
@@ -190,10 +205,10 @@ pipeline {
                     try
                     {
                         sh '''
-                            oc adm release extract --tools ${OPENSHIFT_IMAGE} --registry-config='deploy/data/pull-secret.txt'
-                            tar -xf openshift-client-linux-*${OCP_RELEASE}*.tar.gz kubectl oc
+                            /usr/bin/oc adm release extract --tools ${UPGRADE_IMAGE} --registry-config='deploy/data/pull-secret.txt'
+                            tar -xf openshift-client-linux-*${UPGRADE_RELEASE}*.tar.gz kubectl oc
                             cp kubectl oc /usr/bin/
-                            rm -rf openshift-*${OCP_RELEASE}*.tar.gz
+                            rm -rf openshift-*${UPGRADE_RELEASE}*.tar.gz
                         '''     
                     }
                     catch (err)
@@ -215,10 +230,9 @@ pipeline {
                 setupKubeconfigOcp4()
             }
         }
-        stage('Setup and run ansible extra') {
+        stage('Validate CO status') {
             steps {
-               setupAndRunE2e()
-               notifyBySlack(currentBuild.result, "E2E has completed !!")
+                validateCoStatus()
             }
         }
         stage('Gather pprof and prometheus data') {
@@ -254,15 +268,13 @@ pipeline {
         always {
             script {
                 try{
-                    archiveAllArtifacts("deploy/conformance-parallel-out.txt.tar.gz", "deploy/summary.txt", "deploy/vars.tfvars",
-                        "cpu-pre.pprof", "heap-pre.pprof", "prometheus.tar.gz", "deploy/cron.log")
+                    archiveAllArtifacts("deploy/vars.tfvars", "cpu-pre.pprof", "heap-pre.pprof", "prometheus.tar.gz", "deploy/cron.log")
                     storeMustGatherLogs()
                     checkInfraError()
-                    processE2eResults()
                     notifyBySlack(currentBuild.result, env.MESSAGE)
                 }
                 catch (err){
-                    echo 'Error ! Always block failed!' 
+                    echo 'Error ! Always block failed!'
                 }
                 finally{
                     cleanupOcp4Cluster()
