Updating Z stream jobs
Signed-off-by: Varad Ahirwadkar <varad.ahirwadkar@ibm.com>

diff --git a/jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min-next-upgrade/Jenkinsfile b/jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min-next-upgrade/Jenkinsfile
--- a/jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min-next-upgrade/Jenkinsfile
+++ b/jobs/pipelines/powervm/ocp/zstreams/zstream-ocp4x-p9-min-next-upgrade/Jenkinsfile
@@ -9,11 +9,12 @@ pipeline {
         }
     }
     parameters {
-        string(defaultValue: '', description: 'Build(quay image or build number)', name: 'Build')
-        string(defaultValue: '', description: 'Build Release', name: 'Release')
+        string(defaultValue: '', description: 'Current Build(quay image or build number)', name: 'CurrentBuild')
+        string(defaultValue: '', description: 'Upgrade Build(quay image or build number)', name: 'UpgradeBuild')
+        string(defaultValue: '', description: 'Current Build Release', name: 'Release')
+        string(defaultValue: '', description: 'Upgrade Build Release', name: 'UpgradeRelease')
         string(defaultValue: '720', description: 'Enter time(in Minutes) to retain the cluster', name: 'KeepFor')
     }
-
     environment {
         //users and credentials. All must be defined in Jenkins Credentials
         GITHUB_USER = credentials('GITHUB_USER')
@@ -30,16 +31,18 @@ pipeline {
 
         //Parameters
         OCP_RELEASE="${params.Release}"
+        UPGRADE_RELEASE="${params.UpgradeRelease}"
         CONFIG_TYPE="min"
-        BUILD="${params.Build}"
+        CURRENT_BUILD="${params.CurrentBuild}"
+        UPGRADE_BUILD="${params.UpgradeBuild}"
         TIMEOUT = "${params.KeepFor}"
-        ENABLE_E2E_TEST="true"
 
         //Env constants
-        HARDWARE_CHOSE = "P8"
-        AVAILABILITY_ZONE = "zstream"
+        HARDWARE_CHOSE = "P9"
+        AVAILABILITY_ZONE = "p9_pvm"
         TARGET = "deploy-openshift4-powervc"
         TEMPLATE_FILE = ".${TARGET}.tfvars.template"
+        TERRAFORM_VER = "1.2.0"
         POWERVS = false
         SCRIPT_DEPLOYMENT = false
         WAIT_FOR_DEBUG = "0"
@@ -48,36 +51,23 @@ pipeline {
     }
 
     stages {
-        stage('Clone ansible extra') {
-            steps {
-                cloneRepo("https://github.com/ocp-power-automation/ocp4-playbooks-extras", "ocp4-playbooks-extras", "*/main")
-            }
-        }
         stage('Setup Common Environment Variables') {
             steps {
                 setupCommonEnvironmentVariables()
                 setupClusterConfig("${CONFIG_TYPE}")
                 script {
                     wrap([$class: 'BuildUser']) {
-                        env.INSTANCE_NAME = "rdr-zstream"
+                        env.INSTANCE_NAME = "rdr-zsnxt"
                     }
-                    env.TERRAFORM_VER = "1.2.0"
                     env.OS_TENANT_NAME="icp-test"
                     env.OS_NETWORK = "workload"
                     env.OS_PRIVATE_NETWORK = "workload"
                     env.SCG_ID = "4366c1e2-bb4f-4c3d-98a2-06cc39bbc58d"
                     env.MOUNT_ETCD_RAMDISK = "false"
+                    env.UPGRADE_DELAY_TIME = "600"
+                    env.UPGRADE_PAUSE_TIME = "90"
                     env.SETUP_SQUID_PROXY = "true"
                     env.OPENSHIFT_POWERVC_GIT_TF_DEPLOY_BRANCH="main"
-                    if ( env.OCP_RELEASE == "4.6"||env.OCP_RELEASE == "4.7")  {
-                        env.GOLANG_TARBALL = "https://dl.google.com/go/go1.15.2.linux-ppc64le.tar.gz"
-                    }
-                    else if (env.OCP_RELEASE == "4.8" || env.OCP_RELEASE == "4.9"){
-                        env.GOLANG_TARBALL = "https://dl.google.com/go/go1.16.5.linux-ppc64le.tar.gz"
-                    }
-                    else{
-                        env.GOLANG_TARBALL = "https://dl.google.com/go/go1.17.6.linux-ppc64le.tar.gz"
-                    }
                 }
             }
         }
@@ -101,26 +91,46 @@ pipeline {
                         gbToMb()
                         pullSecret()
                         env.OPENSHIFT_IMAGE = ""
-                        if (env.BUILD?.trim()) {
-                            if (!env.BUILD.contains('quay')) {
-                                env.OPENSHIFT_IMAGE  = "sys-powercloud-docker-local.artifactory.swg-devops.com/ocp-ppc64le/release-ppc64le:${env.BUILD}"
+                        sh(returnStdout: false, script: "apt update && apt install docker docker.io jq -y")
+                        if (env.CURRENT_BUILD?.trim()) {
+                            if (!env.CURRENT_BUILD.contains('quay')) {
+                                env.OPENSHIFT_IMAGE  = "sys-powercloud-docker-local.artifactory.swg-devops.com/ocp-ppc64le/release-ppc64le:${env.CURRENT_BUILD}"
                                 sh '''
-                                    apt update
-                                    apt install docker docker.io jq -y
                                     docker login sys-powercloud-docker-local.artifactory.swg-devops.com -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
                                     docker pull ${OPENSHIFT_IMAGE}
                                     if [ $? -ne 0 ]; then
-                                        echo "${OPENSHIFT_IMAGE}  not found"
+                                        echo "${OPENSHIFT_IMAGE} not found"
                                         exit 1
                                     fi
                                 '''
                             }
                             else {
-                               env.OPENSHIFT_IMAGE=env.BUILD
+                               env.OPENSHIFT_IMAGE=env.CURRENT_BUILD
                             }
                         }
                         else {
                             echo "CURRENT build is empty"
+                            throw err
+                        }
+                        env.UPGRADE_IMAGE = ""
+                        if (env.UPGRADE_BUILD?.trim()) {
+                            if (!env.UPGRADE_BUILD.contains('quay')) {
+                                env.UPGRADE_IMAGE  = "sys-powercloud-docker-local.artifactory.swg-devops.com/ocp-ppc64le/release-ppc64le:${env.UPGRADE_BUILD}"
+                                sh '''
+                                    docker login sys-powercloud-docker-local.artifactory.swg-devops.com -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
+                                    docker pull ${UPGRADE_IMAGE}
+                                    if [ $? -ne 0 ]; then
+                                        echo "${UPGRADE_IMAGE} not found"
+                                        exit 1
+                                    fi
+                                '''
+                            }
+                            else {
+                               env.UPGRADE_IMAGE=env.UPGRADE_BUILD
+                            }
+                        }
+                        else{
+                            echo "Upgrade build is empty"
                             throw err
                         }
                         if (fileExists("deploy/artifactory/rhcos-${OCP_RELEASE}-powercloud-latest.txt")) {
@@ -151,7 +161,6 @@ pipeline {
                         createTemplate(env.OS_AUTH_URL, env.WORKER_VCPUS , "${WORKER_MEMORY_MB}", env.WORKER_PROCESSORS, env.WORKER_TEMPLATE)
                         createTemplate(env.OS_AUTH_URL, env.BASTION_VCPUS , "${BASTION_MEMORY_MB}", env.BASTION_PROCESSORS, env.BASTION_TEMPLATE)
                         createTemplate(env.OS_AUTH_URL, env.BOOTSTRAP_VCPUS , "${BOOTSTRAP_MEMORY_MB}", env.BOOTSTRAP_PROCESSORS, env.BOOTSTRAP_TEMPLATE)
-                        println "cluster build: ${env.OPENSHIFT_IMAGE}"
                     }
                     catch (err)
                     {
@@ -187,10 +196,9 @@ pipeline {
                 setupKubeconfigOcp4()
             }
         }
-        stage('Setup and run ansible extra') {
+        stage('Validate CO status') {
             steps {
-               setupAndRunE2e()
-               notifyBySlack(currentBuild.result, "E2E has completed !!")
+                validateCoStatus()
             }
         }
         stage('Gather pprof and prometheus data') {
@@ -226,15 +234,13 @@ pipeline {
         always {
             script {
                 try{
-                    archiveAllArtifacts("deploy/conformance-parallel-out.txt.tar.gz", "deploy/summary.txt", "deploy/vars.tfvars",
-                        "cpu-pre.pprof", "heap-pre.pprof", "prometheus.tar.gz", "deploy/cron.log", "must-gather.tar.gz")
+                    archiveAllArtifacts("deploy/vars.tfvars", "cpu-pre.pprof", "heap-pre.pprof", "prometheus.tar.gz", "deploy/cron.log", "must-gather.tar.gz")
                     cleanupOcp4Cluster()
                     checkInfraError()
-                    processE2eResults()
                     notifyBySlack(currentBuild.result, env.MESSAGE)
                 }
                 catch (err){
-                    echo 'Error ! Always block failed!' 
+                    echo 'Error ! Always block failed!'
                 }
                 finally{
                     cleanWs()
